=== JSchoreels/kanjigrid/tests/data_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "additionalProperties": false,
  "properties": {
    "data": {
      "items": {
        "anyOf": [
          {
            "items": {
              "anyOf": [
                {
                  "type": "string"
                }
              ]
            },
            "type": "array"
          }
        ]
      },
      "type": "array"
    },
    "lang": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "source": {
      "type": "string"
    }
  },
  "type": "object",
  "required": [
    "source",
    "data",
    "lang",
    "name"
  ]
}

=== JSchoreels/kanjigrid/data/duolingo_kanji.json
{
    "name": "Duolingo Kanji",
    "source": "https://www.duolingo.com/characters",
    "lang": "ja",
    "data": [
        [
            "Non-Duolingo Kanji",
            ""
        ],
        [
            "Section 1",
            "一二三山口田中"
        ],
        [
            "Section 2",
            "私東京都日本父母四五六七見読本時十八半九七六一三二古新百千水大小買土曜話日聞食飲新四時言行来分間十七四二時三何高山休九月日七休九物何買会金父母曜日月何時木卵魚曜日火山田何曜日水階書作四時間何九半人年生駅二一何四三雨川一日五月"
        ],
        [
            "Section 3",
            "先週明月日来家円前今安万日一夜外今学大木先生左右住四月夜一二車帰三月四日後今乗一分六中三飯電今週車八分来年末上五日週昨電話日毎十階日茶毎年入二日間十一月口北好今週末朝年毎入大好昼肉飯八午今月東後間痛目西四日間六階朝飯校回晩今七日六月飯海近八日多半分花色酒六日南十日学生後気場所少人語何人日本楽名前日店計使英僕野菜牛乳語四分社零風呂寝室台部屋会午前所庭窓子猫羽犬鳥椅机七二三歳阪国留健太直美個四二十何五百一八七九三六大外人学生中小高校彼誰姉女供妹弟兄族両親子家堂熱冷甘食仕事勉強友達忙日下横隣韓旅布団冊棚鏡産隅長片汚低蔵庫後国人行一時八本三十七土平洗濯掃除日一昨電映画手紙歌散歩絵音枚写真楽二十一五何百三四戚息娘孫夫妻祖在宅奥主親子六人千百九五八万十七三母父行飛機地鉄空港自転図遅速遠行下車近白赤黄靴青服黒帽欲色茶子公園緒館再練習料理一映画電話来週悪天晴曇夕雪暗方弱気大雨空明今晩朝昼間風強弁当全然果塩醤油砂糖結構変紅物夕飯部少酒大茶出建病院銀向道通口物入行店料理大小箸皿腹寿司碗好物本当茶去誕九日十一月昨年三二毎晩生週間再来鞄荷腕財他重軽丈切違同時計物布色夫大立派男皆勢婚有若離独身氏女方人子大結名赤彼暖寒暑傘次涼狭角広緑春夏紫足冬灰秋早袋携帯色三二靴下手台五池賑匹声動鹿静馬木十二一五八物三園上野牛宿題授業教科難易漢字葉意味辞書言菓唐揚内子袋少店質問答度定規簡単鉛筆教室題今何二一十本四三八五面愛怖暇持悲嬉白気親切分町門交番玄関廊戸村符段危橋運自動車図書館中手洗下切階所五転薄細厚丸鍵石鹸箱太紙鶏豚飴一番四何二三八牛肉制短袖革着浴衣背指輪洋服長半二三四広一帯物上号球走泳弾撮漫番字大丈夫野下手行読上見歌画来多分取文章雑誌返借貸作書歩買邪頭体薬医者鼻顔歯髪眼耳風背病気手鏡運動中太便利周辺外国語事旅館段一海始起立郵局包封筒届船更航配便切手葉書物小中身変住所出空達留伝説初心試合得勝負最苦者中意手渋谷原差点線市首座島民集数宿秋葉新交乗池袋山手近所人口大都銀広住場操陸選種柔卓銅属水泳体上手会場楽目道空球銀金踊直珍君発必要優音預開閉証用士記残支払現署領収替釣別金暗番号口座字紙持会計入高小切手名書両星陽浜湖草森濡浅深氷光波富太空気葉島辺生物火石山具無小説道両方使行読作泳書料金入場和注汁噌濃量客様湯予約勧食文苦味事質植染環境虫巨殺死生物人間地球汚全自然五頭四二子豚大野形格素普厳様子好晴通変美中甘最近悪新高値引小浜横機会名古屋必飲回周枝豆鮮腐蓋鍋材混瓶玉八百屋新乳細大作料理人固調比研究幅測的秤専攻化反応実験科学柔大深高長重者地質生物用意理変資源豊燃決懸命土地所有天然石油料開発取手当回一生件故因不助険逮捕突警察非常震床落救急事原明危大火然口地場合交通面売幹側終到拾席途性寄駐場新線急行点着間出発中女車両男年専用別育徒卒歴史成績締講義提準備教生業後中学校入小試験説明切書地理点出文医読席者合格独"
        ],
        [
            "Section 4",
            "給議刺複功訳続務失礼疲料会室名雑社長上司成売通下残業値段事所様増秒順割掛等算均占相数学三回十四二五百後年人時間引日足番少電卓合計派平多点当林景舎捨甥嬢姪枝色田義理家庭燃息子夢幸興遊涙流眺念趣目的味生行帰歩書安心嘘由秘密表心意見人生自分単語現言搭券観路進切乗光客入国便手続中機内通荷物無事着陸離後成田苦時差師法律欠正対可能解位例典型教予習校長通席専門家分野関心事無科目不授理学文具体的神寺祈信仰宗仏存式葬魂坊滅社道教会人院徒在結婚天国不絶想像確力反対語返事派伝理由上明立可能性喉肘眠肩血骨膝射康臓脳首腕調子指身長注健体重力歯医者心病握老焼巻軍艦刺身海回転部分手的皇象徴世界戦争経済活組県元受付価国家天平和両的社会学中文化行動者番千葉独立明進歩計画地物裏工貧類談代許挨拶則暮刻信号赤駐車場歩道乗客運物港船書相無理可続規遅用事的寂恋精冗情係互胸怒恐触恥驚不安眠心配神的談愛得自信関個人際統政治張案府員投票改挙批判国大領的主首相語提使館市民家議会革選制度舞芸術俳劇感監督拍詩品視偉演役壁作家台絵画一種女優動的手歌人筆場観客線大面割美館泥棒特久振過前回別運転間北海道大事返時代新去断丘列噴漠沖縄方向日本海砂横島火山太平洋活大部分表面陸地刑逃犯罪護裁訴官務所人重大殺弁士判公平有確定無決報季節雲稲雷温示域乾燥蒸候猛烈霧予一時的現象妻雨台風度気地計暑暖化戻越以全員正午予定年間引足見物下上器麦粉加残天注食焼油電子小揚兵敵激盾剣困武撃渉紛士大戦命器収勝利攻解決交中両国外争津災害被洪嵐犠牲伴破壊停避消防鳴波大水地方者電難所広残車明士発生警報署火告状宣脱囚為拠論被白終身刑死人違法捕走行者罪裏付証事実言議根賃井居磨覚畳香納整臭置余毛枕車庫家具屋天一面間寝坊育歯粉目時計地下室豆理分布元腕責任怠担努駄喫煙禁共求安全確義務的当真面目番者力家分終事無公飲酒要説得訪未認博将守期来確物館世話再日付時次回都合迷惑是協止丁寧儀願申慮手数案内非力中本日辞握者遠連絡敗職己紹介我税輸貿失情報業大自最産生量収入金出易相手頂塔郷郊距街谷上川平国境真中大都会北東恋故西外南迷子離界線心地部位置株唯億硬貨札保契貯営勘乏大金市場式約投資財産一全無利子人険発行証借書業定貧党補就臣知総催法案市役所可決次大政国会候者辞任長指名立事首脳理開地演説談咳患睡傷妊娠舌肺肌復爪尻毒頭痛者眠薬体温手術中首後回腹車椅子食消化泊泉貴宿何名四温三過朝食和室休暇号一昼料先重品金庫夕詳放送査述噂発表報道記者事結果正直再調員意外無知銃矢弓基衛隊爆競率暴訓地自員弾争年手段敵軍力事発練滞各渡標識免延効限渋通道路高速改札過列車口白線駅在地行止停無視歩者更新警察官許証決定遠足長有期筋汗鍛憩姿裸伏肉痛和持上体力合定期休的育館腹格息勢出更衣室二頭胸強化見王思魔杖勇妖城姫怪幽霊竜鬼河童子女不議様国要法使気精者化械販技充印刷削障電子自動的機利用法波売不便洗濯音量作成現代術者画像鮮明面夢中池撮除球故調節完哲権待況考賛尊全主義者反体制民党化姿博士号論文知識経験失学利期支持正確現在判断無意状平等方理的成基本重人喜祝贈祭良旗雰囲物行事花火素敵出来日常国気恐脚診症菌腰胃圧退看体調入院察状細流行感染者断書血米凍栄養抹餅含保存冷庫小豆白玄食欲和菓子伝統茶的好焼料品質不足豊快忘掌勤往頃粧州乗車券駅前優先足元席閉最下付近場特急速物精算路線図片道鉄通目的地運賃者復今革化室手北部西九南関減費贅沢製需商益見本販売中員古品車増加少消税価格手入独占上権特新供給要宣伝利景気与従労接僚編募働織設築履程年金業員退職後公務会社過出張中方法死深刻支店面件同転勤就組合集者持主建工事歴調整経営計日書家慣炊招清潔管扉糸修綿切習包丁読書飯器自宅住屋根裏部汚泥水道土配生地工理木中偶録策購疑謝現実然発言記化日広告付見出政世論読者礼認余地越避悔泣福奮慢屈乱嫌諦緊感情後大人的幸覚興我通運死退混表友張頑援令抗敬輩影響挑態威止来張政権求助支配独裁者命反的指示断非難尊語値先後若力老人悪戦度掘罠穴芝滝底沈煙突影性格的森林生根棒哺網巣双雄雌虎吠唸産乳動物類子進化恐竜祖先宇宙探検系望軌火星人天文学者惑家太陽飛行士無限船重力発射台遠鏡道工衛通信俺超奴微妙前兄姉奇跡獄聖墓的地書司祭使命感悪魔説教救神満希足重要不性価値地位権力一切望目標達成容似髪毛床屋美院人前黒白赤目立染合頬茎虫歯乳痛磨衛生士科医学繋了索換房込掲載掃除機電源接続動画終特定共有物形式的検変能開始冷暖設備読入力缶酢漬皮詰桃熱蒸気容器条雇択導賞満最低件報告書管理職用選場一割二十四内容使者訪問中予解指返信力早速話題寄付費警言仲喧嘩婦齢偏般憶衆婚約親恋人中付合間夫成年達未者高少女世代化様長次急速差別集団民族見種知一記力的大課児範幼稚板寮秀要素題童書囲段階的給食園正解公立私三学期制単位黒今校優賞章講演論集会大院堂問館内生飲処箋膚療癌呼吸効果的医師薬局方伝染性皮病力治法内科院溶較液参析仮酸傾比物質全体心理状態学固無色凍気混合考生命分証明説素記号種元類水資料起源作用向標準観察抽折才著創造幕吹奏書道象紙生花的能者性力目次天演技字楽器化粧誤謎適賢概極純粋璧解当集中暗記例不前真理意思上達伝想本気念完成性的実際結局昔忍紀昭江刀憲者戦後世発明見生出令和平成記念日自殺当時戸武士共産党持保障何年革命法君主国立英以前米領土杯酔麺華餃却日本酒居屋飲会乾二定食中一子返口券焼鳥後外没昇踏洞窟岩衝竹貝岸日出朝真赤夕焼暗不安定突大白海生長宝隠陰永魅冒騎幻箱現物遠力的険語悪夢体験石運命王座出会光景士空想道農畑穫牧穀栽培餌家作物産小麦場稲主要業用収量田温室委承氏率直助言幸員会認翻彙繰暢異釈致詞曖昧訳用語返学者定義習能力直接要約引流得言方誤解一活形動特徴容名頼倒積抑笑褒信用恐怖心裏切面快適好不幸悲支援極的消苦痛肉体顔顕透磁公式理科学者大過程限界微鏡図表明仕組度減引付導入石企請額稼資金新事業失中本大提供購入品物求書商店的代節約家"
        ],
        [
            "Section 5",
            "寸崩虹鉱崖前周囲絶滅自壊人類本能雑草熱帯魚的物化石属護徳倫盗罰依怪正義感道的公衆共理現場容疑者違反不利有証人頼代愉癖娯歓迎保証意地悪親友敬快人物頑固情告白味方失望感同印象楽困難場欲自慢的気桜咲梅盆狩晦幌待遠四季花見客粉症実家雨明屋台氷紅葉月陽気日光団子元正福袋大札"
        ]
    ]
}

=== JSchoreels/kanjigrid/data/words_hk_frequency_list.json
{
    "name": "Words.hk Frequency List",
    "source": "https://words.hk/faiman/analysis/",
    "lang": "zh-Hant",
    "data": [
        [
            "Not in Words.hk Frequency List",
            ""
        ],
        [
            "Top 1k",
            "係我一唔嘅個有人都好你佢到就既咁會同大呢以得無要不可然去講過地但話多為出後自時下家上咗點又真之果知做生而啦日經住左啲中如面的咩心幾其成事想開所對樣喺己實呀文睇年用先只仲已學度最意當女於入再定嚟頭問見本是發港間來能行手因哋老邊仔解黎似分覺次返打冇嘢少香道前法完明身食者起理聲方埋全情正亦兩依即語野小國俾應落力叫三十阿諗至死現口相世望作咪公在聽識算友架今機水字嗰未天動走重加笑條種變緊通子將等高哈電外寫工或題更直他主晒二原陣氣太神路該第由書句感快竟始記反關部刻結新眼搵比了長放男位甚細信數乜番白平教班表場言名代夠界單常民性愛難登色說終林連令向回件清期企隻接認續搞西受錯四物低論何音車份化畀每玩候朋錢屋繼街失門近月政幫轉慢合東著體乎風影收任喇金離張拎美雖思安究線岩早根利流試提士從齊五例使司特留喎另活計此囉花讀半英鐘求萬深角處師差買非山突選光且目驚指海星品交內帶樂視被極決傳這容式殺義別步答立除粵廣詞晚總飯故市遠命持飲八也報類業強足進斷必圖鍾坐絕千程社百改保請仍黑媽首觀估謂員考啱簡精支跟底耐及歌易馬整㗎形格雞遊普戰母怪火王空需包況駛牙六區哥麼切愈畫台腦嘛撚基史亂確黃婆味樓初與功各紅推並滿制飛科奇量噉建隨排辦七城追響把佬價九輕盡資還運拍網客校篇術假拉鬼酒興節舊婚權爆治肯那段們照醫警達頂苦值止熱環禮片共產和沒青議急某調誠戲往示歷超古石眾念房腳則獨希展夜吓唱尾爭層球源圍標仆態靚投毒越堂靜親象送零執灣號痛紙醒換景證傾消啫概聞準較洲顯紀雙堆升府引看啊背冷套牛質系餐波喂血斯統習華演異勢病土院像存怕料維賣拖曾牌隊停楚舉巴集忍取藝短費袋約叔專劇麻忽服碼屌歲裝洗律局據票疑周爸圓級官派鐵便沙稱趣才嘩訓呼龍息島肉列傷破旅擇遲護她練謝釋順倒境裡管亞卡燈散聯熟聖跳案免梗淨評右喜搭告救兒責務南德承技職擊彩若廢惡察組些吹姐補痴唯煙願皮造印商規嫁揀暗典居設餘彈參溫北永般良室衝衫筆復介站耳隔靈魔掂敢索速領撞濟吸預避渣李陸哦堅詩團型導擔妹夢敗族遇畢偏嘴歡狗威退掛秒屬微銀待浪棄輪雨靠驗查米輸顧致備激朝際恐鬧魚否羅擺鳩廿負錄壓塔拜煩版臉陳充木貨炒歸討限修塊杯迫跌屎惜喊章貴雜置狂硬福元座懷戀粗慘股罪跑很燒茶弟抽添衰店兄密欣適沉配鬥壞伯模純妙毫豬偷研咧漢犯扮群捉努爛軍爾閒控創狀吧郁歐勝善尤養嘗談貼震尼智曲膠誤幸效炸富洋阻招園插陽髮拿守慣穿素融夾武訊透嬲粒育蛋刀封材鋪雲享具寶村略絲傻蚊休布勁草嚴射露判抗秘橋許害注里瞓途供暴編翻揮"
        ],
        [
            "Top 2k",
            "骨險借覆夫陰互尋父私乾劃鏡弱搖移批迷付嚇春祖澳減麵君闆肥優志盤禁降廁副按逐呆垃率嗎館圾忙贏赤偉油課兵唐肚探淚仁床虛臨廳碗郭製衣附庭賞久漫閉敬構戴烈益鬆默給吖蘭傅黨淡舞述霸助器辛施溝防潮帝陪毛播哲嘿申濕皇樹藍趕懶柱雄豆梁剩裏雪褲船亡旁脫財悲悶摸琛哂碌複迎括攻唉森宣幻抱觸危款缺閃忘咬秀範宗粉莫監滅佔徒灰咖佛尖尊巧祝扒漸圈憶獸勇廟藥須搶窗賽呃嘞曬嘈橫讓攞涼絡枝吃板沖端博咋宜童貌坦掌析殘田軟淺魂飾菜乘幕俗慮逢槍卻握牆嫲聚距鼓暫遺怒鑊鮮醉柒找穩築鄉忠奶游膽貓伊伸胸抵河鞋叻敵階側慶核窮譯增紹席測讚嘆盒厚奈混勞拳皆填操汗營秦遮織賭嘻兼宮楊甜幅緣尚涉固捨悔葉逃鼻挑鳥符啡健序梯訴甘辭凍瘋隱抹午嘉奮欲綠諸豪孩刺寧岸灘訪佈兜匯拒衛困洞碟含丁夕束罩舟郎'屍康拆佳嗚徑疊盛呵積薄粹竇煮掃策虎泛州幣折朗踢鎖啤凡娘揚跡韓串江蛇委莊輯怖托珠誰麥喝噴針擁憎劍夏徵浮省拋染珍媒韻剛恨末緒嗯怎眉載雷猶咯甩癲賤伴倫怨碎蠢麗劉伏恩扭抬屈縮賺逼哼搬着摩簽錫掉污稍潛裙塞藏臭狠榮餅艇儲審歉疫祈革塘憑秋胡豐鎮糖授揸映轟儀悉柴爲舒枱爽孤滯辯額描獻吞偶克爺納踏孫檔獲磨詳慰嗱滑咦后寒延滾績頸厭泥潭輩啖漏翼頓督掩醜暖陷均恥戶泰檯仙宇攬廈罰鼠扯抄撥晨膊潔戒斬罷喪牽聰琴冰嗌捱昏趁農哭億徹滴劈吉嫌巨檢池倍啟忌振猛甲痕襲誌闊扶吐慳傑註拼淫嘔租聊貢頁雅奧惑盲賴勸幼柔矛遍偽邪雀玉踩鹹牲攤沿癮撐犧玲截敏毀衡貪迴霧項顏駁掟廚塵替飽兇哀姑幹攝蓋誕憐坊湯炮累廂瓜抑啪唶凌旗烏蝕襯庸卷鍵篤逆妻膚墨悟櫃渡署腿干迅輔盾砌鴨橙勉咳壇暑曼肺亮懂扣泡諒箱拗腸乃獄獎糊誇障騎繁徐冠咀谷玻譬契奉婦季宿尿擾緩腰蘇姿杜損謀勵曆乖仇吊喉寄嶼爐荒違乏割協旨伙僅姓懼浸竹齋璃雕瘦賓劣叉旺菲裂症侶吾貫哩恭遞蝦哎抖糧脈糕个孔廉援箭舖鄭蟲閂扑偈京壯崩廠扎掣擦訂飄騰戚蘋戇採陶跪嬌丹寺巾憂晝窿餓勾匪仗崇唇敲濃邏頻煲彼捕糟輝匆塑壁湖郊酸擠冬梓臂粥穆殖鋼帽紛競綁斥熄域廊慌擴獅譜掙梳妖奔循欠湧漁災縱繞銅鳴曉植耶氛娛鬚憤哪籌閘鹽搜閱蹤辜寂恆旋睡稿曰嫂嬅氏洪撳奸屆剪勤拾搏遭鳳喻謙俊奪惠慧茫盧釘焦藉央詠云歎叮坑奴拱津爬纏誘框獵鑽訝欄歧淋診療鋒侵冧剎撲暢涌辣冒劫坎宙尺斜棍熊窄紫繩蒲姻患腐鬱睛倉徙衷齒袖檸攪螺押宅擰禍荷澤薪孝灑炎臘魯催礙罵胃躍餵湊筒揭脾恤鄺井促晏祭賢頹斤捲仰匙噏愁朱迪諾諷刑奏憾尐亭冚晰笨蕩陌隆棟啞眨壽峰幽掘泳疏矮紋舍鍊妝柏臣皺庫欺洩芒趨窒郵彙棋宵碰譽黐殊辱毋液堪愚蓮籍蜜乞售擋歪稅葡裁覽礎"
        ],
        [
            "Top 3k",
            "悅役脹桶磁吳罐龜撈俱孖浩旦猜貧慾弄准堡攰暈疾屙丟喃彷址捐梅矣賊購銷髀汁敦喘彎拔摺矩舂豈遙姊棵妥誓妄脆仄礦芝諧廷趙予措艱匿穌稚呂宋嶺渠狼羊遷寵寬舌凝彌擬盈籠脷驅鶴冊乳姦卑瞪盃丸歇泉渴籤軌週騷薩齡薯販咭董傲妨肆蒙鄙咒沈賠漆盟娜閪卜坳埔寸淪脊撻垂紮籃巫挖氹翁脅跨侍余厲鬍召滔丈燭潰呈眠埃誼疲厘刊吟慕斗淘漠煎碑蕉裕葬頌捧秩慨培悠笠謹邀隧濫娶債桃殿腹航褸辨滋吻踐竊軀肩凳抓瞬晴浴盞窩耗貿冤乙嬉傘償凸囊坡瑪筋萄俠裸繫逝伐勒啩姨宴崎弊恰愉愧懸挺繪芳貝鄰罕潤羞噹邦耀芬袍尷鷹泣衍肢虐它揾稀蒼鈴丫勿慈懲棺涯撒榜聳朵牧邁溶梨侯呻墮揼殼泊腔詢貶巷彿尬哇酷駕屠賦螢嘖劏奢樽盔鏈挽儒剷贊燃逗惱嘯漂豫响墳昂焉焗肌艾軸洛嘲懇磚嬸嘟屁鑼券棒拯刪崗慎撇犀紗采塌仿陀劑械帖撕奕捽儘嘥惹茅顛呎蓄拘煞糾佩焚昧魄囡瞇夷鄧鯉綜蒸祥謎晶嫩倦禾虧喚牡扁漿佐丑騙晃鯊捷汽沫碧藤謬蹟馳驟託撼詭叛刷骰噓蕭剝埗憲披挨盼籬豎蔡寡杖縣僱擲爪撫錶胎炭噢卒帳摧渺漲酬釣鑿筷銳潘椅宏征昔暇椒綱苗馨鹿倪匡勻蘿竅銘茄屢寞簿凱鉛妓羽甴鈕佑卸恢松櫈滲煥蹈錦匠涵澀贈醬悼屑懵曱詐豁咸凰屯斑枉毅窺胞袁鵝緻奄瀆履枚餸刮櫻魅隸琪噬弦唸嚨湘孟燕苑蹺岳哉孕瀨恒翅蝗樸欖狹盜躬頗抒脂喱吼彭墓弓惶斧犁癡蠟闖衞鼎戈畏癌苟擅韋疚粟賀譚旣嚿巡枯淆竭箇縫羨膝蟹颱昨倡龐蔥蛙挫昇吱਋馮怔舔韃撤燥砂磅稽簾跣鴻肅蠻榨睜裔潑沾霉撩琦涕瓊瓦睹綿荃腥爵勃愕霜豔鞭檬媚莉乸扇棉腫腩僵岌堤斟灌狡綫纖蔭蘊蟻匹摘瑰侮鞏国墜嚕陋贖齣揹荊唏圳伍僻叢崖惟玄羹茂蠱ࡁ繹俄駐屏柄瀉篩薦囚菌噃菇哄臟耍㖭簫傍坪川朽澄瀾珊瓶紥缸腕躁逸撮疇倚掀寓削膏賜輿牢碩耕軒搓曹遣淒嘶燦膜睬⼈兔塗怠桑綑臺莎鍛廓膩謠僕嬰吋赴渾墊煉眶伶犬嚮覓婉昭恃襪蕾懦俯哽岔巢罅耷鞠骸吵鑑殉曠赦玫禱樑柳膨鴿鍋拙擘姆沮汰什唞攔攜溜禪蟬邨紐煽瑞萌赫剔襟刁唧占拐兆樺壟妮敷咕糭囂蜂蝶鈔悖捏逕凹併葛亢滄兮卦恍悄恕鈞慄堀曝桂棚淇滘熨狐穢葵霞寢豉瞭薛遵傭砰貞倖凜薰瞞繃曖盂瘡誅睄阱泄邋偵珈訕笛卿怡戥暮熔祠肝顫僑宰荀熙柯蓬御秤鴉咽啼焰殷孽癱黏痾晦兌惺僭嗲侃彤喼瑤唻擒甫眷綻蛛霑擎釀遜輾頑夭晾蔔籲庖蒂穴遁袱昌惰叱哮瀟雯呯嫖兢哨棠苛蹄閣頒啜拓肋羣矢餒捍凶娃爹杰帥聾駒晉巔訣穎矇銜癢遢摑菊淑忿靡羈搔虱喲墩攀爍瞄禽纜翠褪陵鯨芽壘橄撰搗冥盆駝彰慚搽炫倆扼耿妒瑣妳廖蒞崔舀枕檻瀑猖耽艦隙頰鋤啓弗啃砸閩酋兀嘰燶聘嘍惘懈狙廝斃昆飢斂刨掹喔証頡丙幢捌檳徘淵熬睫肇蔓轍逾敘挪㩒岡曽瞳茲濺瘀憫聆欽賬摔函"
        ],
        [
            "Top 4k",
            "喧暪獰伺帆徊抆掠沸溯烤眸碉祇綽蘆虹閻鞍顆髓噸允竄駭濁拮翌肖噁紳夥搣姬寥攏鑄噪怯嗡琳濾咐霆嗜俏嚼逞浦莞嗄僧卅擱栩梭楓瀝猴瑕瓣畸笏筍荔衹辰沽躲霍祀屹跛毆攘踎迂虔傢躉駱朕洶縛萎琉癩薑餃癖汪畜睥杆菩蔑懺溺謊鈺于螞寨豹禎姣桿鮑咆拚晌躇躊墟壺孭摷溢狸獗蠔靴龕埠驕瓷炬詮曳婿馴醋温汝瘟遂奀霾箍霎綴亨氧沐吽嗤翩嗽嗒吩伽盪岑几盅彥盯噗莓賂匸昷栓剃峽庇杉汲淹炳絮翔肘葫蝴醇鑣闢靶幟碳諺鋸辟媲駿魁吏瀕呱萊娟鐧烚匣揣疤汶蠅歹憧侈惕敍棘瓏痰抨蜻漓鴛吠喳帛拂蕃冗糉豊圭咿羮祢嘎僥刃剖噚嚎塱壩峒峻濱灶盎砲蟧蠄豚闌禧咎崛贅菠牟蔽衙矯奠鏟鋁冕遑楷迦蹊瘓潺芥蓆朦稻虞憬卓尹炙猝緬蹋毁膿唓揪擂琼猥鴦翹噩勳猩胭燾燼炯ࠒ腆藹躺窘捺毓⼀堵桌溪瀰狽瘴磡逛醮閑霄頃穀摯菱芻峯誦肴裹饒煌捅殆槽慷叭摟瀧厄哣悵襄釐祿嚏譴闡蜓庶朧栽扳叶灼嘭揖剋鵬弧瑩鎚囝蜢鴇壤寮徽榷槳汀沛濤眺賈鑲飆饋ࡃ孰戎誨宛蒜諫輒渦鏽俑囑僚籟沌酌倭諮絞簇翳絨萃唥臆鑾饅濡諱靖薇閏摒栢吔歛埼尸佣嗟仕瑜腑瀏煤喬吭嗨涎霹靂靦偕悚惴鏘咨詹咔鍚鏢謄弘梧榴橡甕甸畔瞻穫罟趟踭飼篷訶壹氈悍澈楹貸賄乩臥翰澱糙蜘烹蜑棧熾吶喋訛倔卵蔗謳逮垣誡梘蔣繡尉娥諭矜姥啐呸囍詫杏囈褻痺芭賒呷棗腮坤实敝樁硤撓蕙腍驃抺䃟划噤奬寅湮濛疵瞰祕禦稔荼螂詬蹂躪轆雌馭骼鶩緝嶄烘楣骷髏孺蜒掬丘艘倘杭砒槌旱砍艷鼾鉅曙顰羔詡腎腺恿慫絳棕嗇轎冶窖疆麟拈惋憚滌蓉褒蹶逍錐髒鱷淥佇罔胖姪孚楝藩踵燙禿瘤愣咤虜釁秉拭会槓佻墅璧嬴緋范嚓娓揉唪劌姚熒叨唾娼株瑟絶羌趴騮驀芹枷穹輻縟糯俐囪踞廬戌札歟殯轄塚搪竿軚酵瀡餡梵凋恙皿募拷婪篡緯嫉潦鱗稟詣徨漩疼磊嚥囤朔殞膾韜饑傀儕儡撿癥汾慤啄悸鉗臻脯浚鑒杼砵暱舜俚膳寰榕諜隋吁氮࠺舅为嫵您攫蕪鏗嫣惻涂悴憔鬈庾沓勺乍垢峙嶇戙抉燊稜笙箏紓縷繽訟踱錘髻黯噱嚐淮棲醃陲蜿弒繳卉謔梟贓戊紆逅榻俬揩嗣芸莘仃捩嘸戮巉殲轅遼琢脚阪奚箕癒儼冀痍莠蝙蝠諉咇曦啷撬釜辧殃抌倩黛渲趾剿殭俘犢内詁挾濠滸魏銬嫦両惆浙籮吆瞌蛀儉婷綺嚷嫻巍愀戾掏时柚泱澰睽袒詆长汨膀騾蔚恁忡咏澎葆咄躂佼攣粼氯囿妞弩桐笈篙紜莽萍蛤衆陡駅鯽擸枳敞櫳誣驥矽締哺祟馱錮甥茹旭詔雛牀耆遏酗趷埞拌孱蜃韌呔嵌桔煨鈍㨴媳涅燴徬嘜泌炆驛骯髯堯糞ࠝ龔諦嶽殻黄暨儂彬鐡漣漪瞥迢縈么焊佮儈詛翦俎咚蠍澧蕊筵諳邂乒乓丞夌鎗埲銖㷫蛾鼆簷邑蠶闔匍匐幌獪簸螻賅軑圜栗体彊憩抿淤璞给话軋进驢鬢唆氓噥憊汕痱皂譟酥嗦郡貳侏羚噠鉤喙奐巒巿帑强撑檐漕澗瀚瘁礡纓芋苔薈蜆跚蹣輋雁鱲鵰ࢃ橢狄饗樞麪輟鱉恪沃鹼"
        ],
        [
            "Top 5k",
            "芯涓鑰狩腌户褥笪忖烙艙࠵胯鳶躋挈籽冽匱拇閹纂霓邃氾拃諄窪恫炷喀茵璀璨関嘮幡攋藕瞎揦蹴耘儆拑攸沼点譎銹沬絀两垮岁菁鹵嗔駢万忟翊ㆶ礫跎怵肪餚隕弛疋膺磋蜀掕妤辮仝唚燉倌妍戳烽瀛鈎鬨恵厥飴曇匾扔聡卧鞘臍釵劊縹黝睿窟忪鉸叼啕噫摵擻瞼誹謗孜誒輛吝猿枴卍对帚悽愴摶无泓漉箸糴耑謾评语貅貔还冢帕彪慵搐椰潢膛蚓蚯賁鎊鶯奎嬤应楨祂翟酣敎縐躝ࢲࣲ煇臀岐湃熹籐絆舐轔閨秃肓揈莖猙卽藺哧蹦⼤⽤嚶侷咫孵巖弔徠扽暉滂牯璽砭綢繆舢茜蒐蛟螳髹鷄竽猷穗鎅稷踊遽峭夙焫僮劾庚扈杳殮灤絹迄竣掗鍍銃矗懾絢込陛閥柺綵胳矚蔬漱麾甬芫溉牴湄啾噌筲蝨鱔鷂祉譏迥吒夯擢炕硯綸芙覷闕驊旬虫踰凈煒譁翎ㄎ侗硫蹉錕衊叠欸鸚緹鍥鰲箝喵懊櫥霏魷遐㨢跋魘洽暄泵阮髦広辞紂宝慟錙咓嗶写鬯滓熏踪咱湛坷媧睦遡緲隘鵪鶉噯畿眩眯様竪颯憨众匈叙圏寇忐忑搁摹泪睨稠紕终脖膶藻褐见记难东丽嗓宦揄揶氰洒涸簧酲阡シ们偎华发喏愿戛煬现紧该俳呤唷徂癐裇藐邯鄲喫翡罄胴伕麓没崳捻泯苞鳯韶怦蚩讖醺尻囁捶咃哆騸剥徛眞尴岀囖莅矓駄燄⾃⾳啵溻翕嚱膞仞僊剌勘堰岬嶂巗怱抛朶沱澇瀅炊瑚纍罾袤説踴錨騖鷗ࢯ橘葺鐮迭涇渭驍謁豢伇埶邇閡壅氤氳獠瞑禺胥褫蹲鸞耄耋妃漬痹㧬罌皙娑繚粕婕薊荳韮眈斐缽唂昕愫桎梏黹佚啅焼櫚冑犄盦埈壑俺凪摏燬姜驪侲橛毽舵蘸麒ࡁ臃鵲騅鯁祐舛倀区恋戟揑磐絃继续裨伎裱号图怜懃縴鸡叩佘旻隍庵葩嚡ㄌㄚ扤恬愎紊隅騐醞扚驄鵡嗬冼儍弈縝啝睞菀来渙醍醐愜硝髪漾酊酩桀蛻綾姍餬孮沆砥騁潚覇椎檎韁㦸亥鰍皈礼虯軾酪滬齌掐緘扉槃俸餉ࡁ跤夸浹忤恣捋禠渝窈窕丕妾愾摀嗆嗝瘠皚繭臠顎珞瓔詰皓茁椿韭颼嘀嘚禀习书乱从价势叵叹员啻带张揺搥敕晢晩极樫残氫热牘牠独獷癟瞧祺笔箴簌荣蔻裘裴覲觉认论踮鈿随靄鴕偌决匕啥懍掰擄杀杞檜气漒瞅緞纷罹虽观赛赞遴錚银齏齙ホム业偃况办囌坂声妁护捜机毕洙灯窓经让蹓这鐳餾丐哘扱揞搦擳珮碇礬筱篱菓赢躹鏖飊࠾ࢳ࠻亍彳焯樖頽叁昩弭甄軻࠽溏琵琶熜焙尢媾孻氖溥蟆ォ攙魑蹩紡喁甌㕭嗅瘍胱羡槐邱涿蝸撘鯇傞摭杷屄涔燠愨㗳欶懕捃槪滕澌砐谂閙蹭厠摞燻薜崽寐忱淳糹肨芩飩嚹孥噖譭瞟墈撂狏珏緅骹悻嚅挒濂肛戅⼊⾒⾮⾯旮旯繑洱逄鯪骴捹粘餩朴滷孢侖円劬匝圃埕屐崢嶸撟柢毬汐汚淼秊窰纒舨莆菍豺酙鋰雍頤寜稈筳饌輓鎬爓狎羸鲁澹蹞駑喐嵐旃檀爇琤癰砉禳縊訖詈誶讞邸闥帮厓粿罉拝蜍蟾紈絝㝝嬋衩鄂搲荽刋澡祚腓赭亶斡畋褶訥鏤悪曜気秏茨辺芈塡螃餼࠽垓禤茴謭汞猾稳胜设鏐阶项蚺䕺聶卫坨妊娠学庆褂掦ई毘纈竉髺鯰筠酉鋈詼佗ㄏㄝㆴ㤇唨緙虢迆磺甦掖緃踨䅲瑛皃"
        ],
        [
            "Top 6k",
            "盍辵贍蹝俹簁紉芡鎂ࢭ亲冲吡弼袞嗻懿徇嫰歃ࢱ嫗暏葭蒹珀琥壬恴燘鸛淩痢笆颶顥黌囹圄瀸燎礪艺鵠熵杠氟銼鰭灸効硃侄碴誔蔃减戯湾綏脗㾻咑瀲灩睺蟠ࢴ訏唁邵卯佃鋌倨酚痊諎蕞参聴喞窯羿誑墻濯鷺棱軼韙罊࠺挲鴆篸鄒鄹臾剮嘷媛峋嶙犲猢猻糅縻峴毗蟄掔盹蹙霽玟兀隷摻觴棹櫫佞曚癇洳澪飪黷蒿踝呑娉婀嬈瓠螓仨儿关吮埸墾壴妣将届属岂岫岱帐录忒忧忳怀总悌惊戍戕捫掄显晓梆楞殂殤毌沏瀣状瑄疴眢碍聒腋腴节荡蘑蚣蜈装襠襤諂諛诛说请谐豕貽质踁踘蹹车远连邓醴鉴錡鑠针钞问闹阁险霪预题风齜击奥妲廸枪样檄潸环称约翥获菅覤訐貂资踉蹌軏运选错间雹韲顱ェオャ义亿兴冏吂听场坚复奋寻岗广开异弃归惦懨拥旌暁枹梢梦济灭爱縶线细结络绝联胁苯茱萸蜚裳諢证课贵轨适逊醛释鎧鏹霖顺馈騭鱂鲘麋黍㨂䓤丼乭偲幔涙産穞窂肶艮萱蔴蠓陞ࡲॄਈਤ௣栞囗㗰磯刎啋婊驘糠褚廛曩毎茉町亟玖餞迹擤価値変幪観畨惝榭滇簪绮鞦韆顔鵑洎洵茍讒彚樵擗狪駙鐸麝耒࠴瞽葯㰖嚢婢徧懞虻蹀躞掤孛獃闗粽贛蟑蹇チ伝澆蔦魍魎憟删痘剽宄槎灞畝睢粱粲罡諍賸逋郢鄕鋏韉䟓勛堊彗楔槤瀘鏞麈蚤欧頼脇蚍蜉鏑跆煜崑刧埇鮫嗩痙褊睩雒㨃䜙獳矖袂謷逳净浓粤级讲阵鈣癆蠆貯絰摙焮哟呮嘑妗罸佯俞璣謏鎩麽齟齬嗮巹祁膈鯹挅柸幀拄蜷塢啉胚僆嗉昅卌趺躑礴噝壆孑怙悛捂旎旖猄笫篋躀隼顴黠幃枇炖疙瘩笳靨傣嫡睼झ暝柿嗥烟鎢驁鰂砧鎯鐺刄峇濘孌朣沢癦簣鈾埴禹糜蕎滙⺟⼆⼝⼰⽂⽅⽣⽩⽭⽼⽽⾄⾏⾸⾺亱凖嚫并徼悞箋纔视縄掁࡙淅攢糍綳窝鰥燜哐揜撠舳艫踼煁簋譖圑嬏柑礁緑縁罨録瘌嘓噣樟閤餿呌屝涶癊魴鰻挷枭渗傚孿磿昺毯蛆寛檷"
        ]
    ]
}
